### ISSUE TITLE
waveform doesn't render when using URL instead of local source

### ISSUE THREAD

**Issue by Mr-Ples** [brgndyy/brgndy-react-wave-form#1]
if you use `https://codeskulptor-demos.commondatastorage.googleapis.com/GalaxyInvaders/theme_01.mp3` for example as the `audioFileSrc` the waveform doesn't render. it still plays and pauses though

for example:
```
import {
  IconPlayerPauseFilled,
  IconPlayerPlayFilled,
} from "@tabler/icons-react";

import testAUdio from "~/assets/sound/eros.mp3";
import {
  AudioWaveForm,
  AudioWaveFormWrapper,
  PlayOrPauseButton,
} from "brgndy-react-wave-form";

export default function WaveForm({ selectedVoice }: { selectedVoice: any }) {
  const audioSrc =
    "https://codeskulptor-demos.commondatastorage.googleapis.com/GalaxyInvaders/theme_01.mp3";

  return (
    <div className="mx-unit-sm w-full rounded-lg bg-[#21232C] p-unit-sm">
      <span className="mb-unit-xs opacity-50">
        {selectedVoice?.name || "Voice 1"}
      </span>

      <AudioWaveFormWrapper>
        <div className="mt-unit-xs flex flex-row gap-unit-xs">
          <PlayOrPauseButton
            audioFileSrc={audioSrc}
            className=""
            playOrPauseValues={[
              <IconPlayerPlayFilled
                className="mb-unit-xs"
                key="IconPlayerPlayFilled"
              />,
              <IconPlayerPauseFilled
                className="mb-unit-xs"
                key="IconPlayerPauseFilled"
              />,
            ]}
          />
          <AudioWaveForm
            waveFormWidth={800}
            barWidth={2}
            barGap={3}
            baseBarHeight={0.4}
            barVariability={0.7}
            waveFormClassName={"h-[2rem] w-full"}
            audioFileSrc={audioSrc}
            backgroundTopColor={"gray"}
            backgroundBottomColor={"white"}
            barTopColor={"white"}
            barBottomColor={"gray"}
          />
        </div>
      </AudioWaveFormWrapper>
    </div>
  );
}

```

in the above code `audioSrc` does not render the waveform but `testAUdio` (imported above) does

console shows this error:
```
initializeWaveForm.ts:30  WaveForm 생성 중 오류가 발생했어요 !  TypeError: Failed to fetch
    at f (initializeWaveForm.ts:4:23)
    at h (drawInitializedWaveForm.ts:18:37)
    at AudioWaveForm.tsx:114:13
    at AudioWaveForm.tsx:126:8
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at invokePassiveEffectMountInDEV (react-dom.development.js:25154:13)
    at invokeEffectsInDev (react-dom.development.js:27351:11)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:27330:7)
    at flushPassiveEffectsImpl (react-dom.development.js:27056:5)
    at flushPassiveEffects (react-dom.development.js:26984:14)
```

```
Access to fetch at 'https://codeskulptor-demos.commondatastorage.googleapis.com/GalaxyInvaders/theme_01.mp3' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by brgndyy** [comment]
hello.

First of all, thank you for using our library.

This is not a library functionality issue, but a network communication issue.

This is called a `cors` error, and it occurs when network communication is attempted between different domains.

This would be possible if the server allows direct resource requests.
